# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
