# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='changelog',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(max_length=40),
        ),
    ]
