# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20160229_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageversion',
            old_name='package_id',
            new_name='package',
        ),
    ]
