# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20160229_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageversion',
            old_name='path',
            new_name='dist_file',
        ),
        migrations.AddField(
            model_name='package',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
