# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date created'),
        ),
    ]
