# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_auto_20160229_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
