# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20160229_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='manual_file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
