# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_packageversion_manual_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('variant', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=10)),
                ('obsolete', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date created')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Product')),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomerPackage',
            new_name='CustomerProduct',
        ),
    ]
