# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_auto_20160301_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='package',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.Product'),
        ),
    ]
