# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='production_order_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
