# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_customerproduct_production_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Product'),
        ),
    ]
