# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_auto_20160303_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='inv_customer_id',
        ),
        migrations.RenameField(
            model_name='customerproduct',
            old_name='production_order_id',
            new_name='inv_production_order_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='inv_product_id',
        ),
    ]
