# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_auto_20160303_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Customer'),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Product'),
        ),
    ]
